In [7]:
import pandas as pd
df = pd.read_csv('Record.csv')
df

Region                           Country  \
0               Australia and Oceania                            Tuvalu   
1   Central America and the Caribbean                           Grenada   
2                              Europe                            Russia   
3                  Sub-Saharan Africa             Sao Tome and Principe   
4                  Sub-Saharan Africa                            Rwanda   
5               Australia and Oceania                   Solomon Islands   
6                  Sub-Saharan Africa                            Angola   
7                  Sub-Saharan Africa                      Burkina Faso   
8                  Sub-Saharan Africa             Republic of the Congo   
9                  Sub-Saharan Africa                           Senegal   
10                               Asia                        Kyrgyzstan   
11                 Sub-Saharan Africa                        Cape Verde   
12                               Asia                        Bangladesh   
13  Central America and the Caribbean                          Honduras   
14                               Asia                          Mongolia   
15                             Europe                          Bulgaria   
16                               Asia                         Sri Lanka   
17                 Sub-Saharan Africa                          Cameroon   
18                               Asia                      Turkmenistan   
19              Australia and Oceania                        East Timor   
20                             Europe                            Norway   
21                             Europe                          Portugal   
22  Central America and the Caribbean                          Honduras   
23              Australia and Oceania                       New Zealand   
24                             Europe                          Moldova    
25                             Europe                            France   
26              Australia and Oceania                          Kiribati   
27                 Sub-Saharan Africa                              Mali   
28                             Europe                            Norway   
29                 Sub-Saharan Africa                        The Gambia   
..                                ...                               ...   
70                               Asia                      Turkmenistan   
71       Middle East and North Africa                             Libya   
72                 Sub-Saharan Africa  Democratic Republic of the Congo   
73                 Sub-Saharan Africa                          Djibouti   
74       Middle East and North Africa                          Pakistan   
75                      North America                            Mexico   
76              Australia and Oceania    Federated States of Micronesia   
77                               Asia                              Laos   
78                             Europe                            Monaco   
79              Australia and Oceania                            Samoa    
80                             Europe                             Spain   
81       Middle East and North Africa                           Lebanon   
82       Middle East and North Africa                              Iran   
83                 Sub-Saharan Africa                            Zambia   
84                 Sub-Saharan Africa                             Kenya   
85                      North America                            Mexico   
86                 Sub-Saharan Africa             Sao Tome and Principe   
87                 Sub-Saharan Africa                        The Gambia   
88       Middle East and North Africa                            Kuwait   
89                             Europe                          Slovenia   
90                 Sub-Saharan Africa                      Sierra Leone   
91              Australia and Oceania                   

We have read the data from "Record.csv" file

In [10]:
df.to_csv('new.csv')#it will load data with index value
#if we dont' want index
df.to_csv('new_noIndex.csv',index = False)

We have created the weather_data with features day,temprature,windspeed and event

In [4]:
import pandas as pd
weather_data = [('1/1/2017',32,6,'Rain'),
               ('1/2/2017',35,7,'Sunny'),
               ('1/3/2017',28,2,'Snow'),
               ('1/4/2017',24,2,'Snow'),
               ('1/5/2017',32,4,'Rain'),
               ('1/6/2017',31,2,'Sunny')]
df = pd.DataFrame(weather_data,columns=['day','temprature','windspeed','event'])
df

day  temprature  windspeed  event
0  1/1/2017          32          6   Rain
1  1/2/2017          35          7  Sunny
2  1/3/2017          28          2   Snow
3  1/4/2017          24          2   Snow
4  1/5/2017          32          4   Rain
5  1/6/2017          31          2  Sunny

In [5]:
df.shape

(6, 4)

There are sixth rows and 4th columns

In [8]:
df.head(3)

day  temprature  windspeed  event
0  1/1/2017          32          6   Rain
1  1/2/2017          35          7  Sunny
2  1/3/2017          28          2   Snow

We have fetched the 3 top data from "weather_data" dataframe

In [10]:
df.tail()

day  temprature  windspeed  event
1  1/2/2017          35          7  Sunny
2  1/3/2017          28          2   Snow
3  1/4/2017          24          2   Snow
4  1/5/2017          32          4   Rain
5  1/6/2017          31          2  Sunny

We got last 5th rows by default as we don't mention any number of rows

In [11]:
df[2:5]

day  temprature  windspeed event
2  1/3/2017          28          2  Snow
3  1/4/2017          24          2  Snow
4  1/5/2017          32          4  Rain

We have feteched the data from row 2 to row 4 based on silce

In [13]:
df.columns

Index(['day', 'temprature', 'windspeed', 'event'], dtype='object')

We got all columns using df.colums

In [14]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [15]:
df['day']

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [19]:
df['temprature'].max()

35

We used max() to get maximum temprature

In [20]:
df.temprature.min()

24

min() to get minimum temprature

In [22]:
df[['day','event']]

day  event
0  1/1/2017   Rain
1  1/2/2017  Sunny
2  1/3/2017   Snow
3  1/4/2017   Snow
4  1/5/2017   Rain
5  1/6/2017  Sunny

In [23]:
df['temprature'].describe()

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temprature, dtype: float64

Using describe function,we get statistics details

In [25]:
df[df.temprature == df.temprature.max()]

day  temprature  windspeed  event
1  1/2/2017          35          7  Sunny

In [26]:
df.day[df.temprature == df.temprature.max()]

1    1/2/2017
Name: day, dtype: object

We found the date on which having the maximum temprature

In [12]:
import pandas as pd
df= pd.read_excel('Book1.xlsx')

### Numpy Basic codes

We have created the 3 dimensional arrat

In [19]:
import numpy as np
a = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a.ndim

3

ndim is used to get dimensonality of array

In [18]:
a.shape

(2, 2, 2)

We found the shape of array

In [6]:
l = [1,2,3,45]
%timeit [i**2 for i in l]

1.12 µs ± 61 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
import numpy as np
a = np.array(1000)
%timeit a**2

488 ns ± 58.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [4]:
import numpy as np
a = np.arange(1,10,3)
a

array([1, 4, 7])

arange(start,end,step) is used to arrange the data 

In [7]:
import numpy as np

a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


Using the linspace, we will get value between 0 to 1 and six is showing the number of values

In [27]:
a = np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

numpy.ones fill all values as 1

In [29]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
a = np.eye(7)
a

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [34]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [38]:
a = np.random.rand(4)
a

array([0.86033351, 0.45154492, 0.8654467 , 0.04231998])

got positive random value

In [39]:
a = np.random.randn(4)
a

array([-0.5568228 , -0.31951956, -0.18035875, -1.71528343])

We have got negative random value

In [42]:
a = np.arange(10)
a.dtype

dtype('int32')

In [44]:
a = np.arange(10, dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
import numpy as np
a = np.arange(10)
print(a[5])

5


In [49]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
b= a[1:8:2]
b

array([1, 3, 5, 7])

In [53]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

We have set value 10 after position 5th

In [56]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

We have reversed the values after postion 5th

In [72]:
import numpy as np
a = np.arange(10)
a
b = a[::2]
print(b)
print(np.shares_memory(a,b))

[0 2 4 6 8]
True


In [73]:
a[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [65]:
a = np.arange(10)
b = a[::2].copy()#force a copy
print(b)
print(np.shares_memory(a,b))

[0 2 4 6 8]
False


In [74]:
a[0] = 10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [75]:
import numpy as np

a = np.random.randint(0,20,15)
a

array([19,  1, 12, 17,  8,  8,  0, 16, 14,  6, 12, 12,  0, 14, 12])

In [76]:
mask = (a%2==0)
extract_from_a = a[mask]
extract_from_a

array([12,  8,  8,  0, 16, 14,  6, 12, 12,  0, 14, 12])

In [78]:
a[mask] = -1
a

array([19,  1, -1, 17, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [79]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [85]:
import numpy as np
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
d = (a<=b)&(a<=c)
print(d.all())

True


In [90]:
import numpy as np
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,7]])
print(x.mean())
print(np.median(x))
print(np.median(y,axis=-1))
print(x.std())


1.75
1.5
[2. 6.]
0.82915619758885


In [112]:
import numpy as np
a= np.tile(np.arange(0,40,10),(3,1))
a = a.T
b = np.array([0,1,2])
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [100]:
a= a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [95]:
b=  np.array([0,1,2])
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [111]:
import numpy as np
a= np.arange(0,40,10)
a = a[:,np.newaxis]
b= np.array([0,1,2])
a+b




array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [121]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.ravel())

[1 2 3 4 5 6]


In [122]:
a=a.T
a

array([[1, 4],
       [2, 5],
       [3, 6]])

In [123]:
a=a.ravel()
a

array([1, 4, 2, 5, 3, 6])

In [124]:
print(a.shape)

(6,)


In [126]:
a = a.reshape((2,3))
a

array([[1, 4, 2],
       [5, 3, 6]])

In [ ]:
a[0,0]= 100
a

In [129]:
a = np.array([[5,4,6],[2,3,2]])
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [128]:
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=0)
b

array([[2, 3, 2],
       [5, 4, 6]])

In [130]:
a = np.array([4,3,1,2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [131]:
a[j]

array([1, 2, 3, 4])